# Generated by Django 3.1.7 on 2021-03-31 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210331_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
