# Generated by Django 3.1.7 on 2021-03-31 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20210331_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1, message='Title has to be 1-60 chars')]),
        ),
    ]
